### PR TITLE
WebDAV Fixes for important clients such as Gnome, Windows

### PR DESCRIPTION
**Pull request by lab-at-nohl**
Currently WebDAV is broken, directory listing fails on missing HTTP_CONTENT_LENGTH and GET requests are routed by Expressive instead of WebDAV (added definite routing to already existing fixes). 

Adding rewrites is only a temp solution imho, routing needs some work. JN

### CODE REVIEW

**Comment by lab-at-nohl** [comment]
CLA is already signed - years ago.

**Comment by lab-at-nohl** [comment]
Supposed to fix https://github.com/tine-groupware/tine/issues/6.

**Comment by lab-at-nohl** [comment]
I had to add some tweaks to get recent iOS app running (done). **Tested WebDAV** with Android, iPhone and Tine Drive (Linux). Also native Windows, Gnome (gvfs). All works. 

The commit [14beb4f](https://github.com/tine-groupware/tine/pull/65/commits/14beb4f70b84a27a6b5ae1c225c770caed4c761c) was a mistake, maybe you can merge all my commits (sorry, I am not so good with git).

**Comment by pschuele** [comment]
@paulmhh can you have a look? maybe we also need to adjust the rewrite rules for nginx?

**Comment by pschuele** [comment]
and thx @lab-at-nohl for the PR :)

**Comment by pschuele** [comment]
@lab-at-nohl could you please rebase the PR? we already worked on some of the files in the meantime ...

**Comment by lab-at-nohl** [comment]
Rebase to ...?

I am not so familiar with git, but I will do it at the next to the following weekend. Do you mean a specific branch or do you have a specific commit I should base on? Biggest challenge will be to setup a dev environment different to the actual release (I know the docker container).  

Also, I can include all changes into a single commit, if you prefer...

**Comment by pschuele** [comment]
hi Johannes,
rebase on the current main branch.
as you can see in your fork, the branch of the PR is currently 89 commits behind the HEAD of the main branch:

image

you could also merge the current tine main branch into your branch if that's easier. there should be some merge conflicts that need to be resolved.

maybe some of the problems you addressed are already fixed, because we update to a current sabredav version recently.

> Also, I can include all changes into a single commit, if you prefer...

that should not be necessary.

**Comment by pschuele** [comment]
hi, I would like to merge (at least some of) the fixes into the upstream. but this PR has to many small unrelated changes. so I would prefer, that the fixes / changes are split up into separate PRs each addressing one issue / feature. the code also needs to be rebased on the current main branch because the webdav stuff changed a lot during the sabredav upgrade.

**Comment by lab-at-nohl** [comment]
I am on it, the plan was to have another branch / new PR. Thus, it is possible to split, too. 

Setting up a new dev environment. Please allow me a few days (weekend). I'll come back to you.

**Comment by lab-at-nohl** [comment]
I will do smaller PR, closing this one!

**Pull request closed without merging**
